CREATE TABLE user
(
  id INT NOT NULL AUTO_INCREMENT,
  firstName VARCHAR(20) NOT NULL,
  middleName VARCHAR(20),
  lastName VARCHAR(20) NOT NULL,
  gender VARCHAR(1) NOT NULL,
  email VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY (email),
  PRIMARY KEY (id)
);